#!/usr/bin/perl -w

use strict;
use warnings;

use AnyEvent::Loop;
use AnyEvent::Dudlc;

my $dudl = AnyEvent::Dudlc->new(
	host		=> 'localhost',
	user		=> 'lirc',
	pass		=> 'lirc',
	on_connected	=> sub {
		print "connected\n";
	},
	on_authenticated	=> sub {
		print "authenticated\n";
	},
	on_error	=> sub {
		print "error: @_\n";
	},
	on_disconnect	=> sub {
		print "disconnected\n";
	},
	on_status	=> sub {
		print "status: @_\n";
	},
	on_track	=> sub {
		print "track: TODO\n";
	},
);

my $a = AnyEvent->timer(
	after	=> 10,
	cb	=> sub { $dudl->play },
);
my $b = AnyEvent->timer(
	after	=> 20,
	cb	=> sub { $dudl->pause },
);


AnyEvent::Loop::run;

